config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :invitations => 'devise/invitations' }
  resources :events do
    collection do
      get "my_events", to: "events#my_events", as: "my_events"
      get "approved_event/:id", :to => 'events#approved_event', :as => "approved_event"
      get "/c/:category", to: "events#categories", as: :category
    end
  end
  root 'home#index'
  post 'create_contact_organizer' => 'home#create_contact_organizer', as: :create_contact_organizer
  get 'find_event' => 'home#find_event', as: :find_event
  post "get_location_by_lat_lng" => "events#get_location_by_lat_lng", as: :get_location_by_lat_lng
  get 'set_timezone' => 'home#set_timezone', as: :set_timezone
  get 'contact_organizer/:id' => 'home#contact_organizer', as: :contact_organizer
  get 'embed' => 'home#embed', as: :embed

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :set_user_location, only: [:new, :page_not_found, :embed]
  before_filter :set_location, only: [:index, :page_not_found, :tags]

  def index
    if @location
      @all = []

      @all << if @location[:area].eql?("worldwide")
        Event.approved
      else
        Event.approved.near([@location[:latitude], @location[:longitude]], @location[:nearby].to_i, units: :km) rescue nil
      end

      @all = @all.flatten
      @markers = get_marker_and_location(@all) if @all rescue nil
    end

    @event = Event.new
    @categories = Category.all

    set_title_location(@location)
  end

  def save_share
    unless params[:project][:project_ids].blank?
      @content = eval(params[:model]).find(params[:id])
      projects = Project.where("id IN (?)", params[:project][:project_ids])
      projects.each do |project|
        share = Share.new
        share.parent_share = project
        share.children_share = @content
        share.save
      end
    end
  end

  def contact_organizer
    @event_id = params[:id]
  end

  def create_contact_organizer
    if params[:event_id] && params[:subject]
      event = Event.find params[:event_id]
      EventCreatedMailer.delay.contact_organizer(params[:subject], params[:message], event.organizer_name, event.organizer_email)
    end

    redirect_to root_url, notice: "Sent message to organizer successfully!!"
  end

  def set_timezone
    session[:timezone] = params[:timezone]

    render nothing: true
  end

  def find_event
    @location = params[:location]
    @all = []

    @all << if @location[:latitude].present?
      Event.approved.near([@location[:latitude], @location[:longitude]], 30, units: :km) rescue nil
    else
      Event.approved
    end

    @all = @all.flatten
    @markers = get_marker_and_location(@all) if @all

    @event = Event.new
    @categories = Category.all

    set_title_location(@location)

    respond_to :js
  end

  def embed
    if @location
      @all = []

      @all << if @location[:area].eql?("worldwide")
        Event.approved
      else
        Event.approved.near([@location[:latitude], @location[:longitude]], @location[:nearby].to_i, units: :km) rescue nil
      end

      @all = @all.flatten
      @markers = get_marker_and_location(@all) if @all rescue nil
    end

    @event = Event.new
    @categories = Category.all

    set_title_location(@location)
    respond_to do |format|
      format.html {render :layout => 'embed'}
    end
  end

  def page_not_found; end
end

app/views/home/_contact_organizer.html.slim
.modal-dialog.modal-sm
  .modal-content.wrap-create-event style="height: auto !important;"
    .header-form-event
      h1.text-center Contact Organizer
    .body-form-event style="height:180px;"
      = form_tag create_contact_organizer_path, method: :post, class: "form", id: "send-message" do
        .form-group
          .col-md-10
            = hidden_field_tag :event_id, @event_id
            label.left Subject
          .col-md-10
            = text_field_tag "subject", "", class: "form-control", style: "margin-bottom: 10px !important;"
        .form-group
          .col-md-10
            label.left Message
          .col-md-10
      	    = text_area_tag "message", "", class: "form-control"
    .footer-form-event
      button.btn.btn-find#btn-contact style="margin:7px 15px;" Send
      button.btn.btn-find style="margin-left: 10px;" data-dismiss="modal" Cancel


javascript:
  $('#btn-contact').click(function(){
    var subject = $('#subject').val();
    var message = $('#message').val();

    if (subject == "" || message == "")
    {
      alert('please add subject and message!');
    }
    else
    {
      $('#send-message').submit();
    }
  });

app/views/home/_find_event.html.slim
= text_field_tag "location[address]", (params[:location][:address] if params[:location]), class: "form-control find_location", autofocus: "true", placeholder: "Find an Event"
= hidden_field_tag "location[longitude]", (params[:location][:longitude] if params[:location]), id: "long"
= hidden_field_tag "location[latitude]", (params[:location][:latitude] if params[:location]), id: "lat"

button.btn.btn-default.btn-find.btn-find-md.button-find-event style="margin-left: 5px;" Find

app/views/home/contact_organizer.js.erb
$('#contact-organizer').html("<%= escape_javascript(render 'home/contact_organizer') %>")

app/views/home/embed.html.slim
- content_for :title do
  = "Unify"
- content_for :javascript do
  = javascript_include_tag :maps

- if notice
  p class="alert alert-success alert-dismissible" role="alert"
    button type="button" class="close" data-dismiss="alert"
      span aria-hidden="true"
        | &times;
      span class="sr-only"
        | Close
    = notice

#beta-container.fixed-on-top
  #map style=""
div#content-for-map data-contents="#{@markers}"
div#location-for-map data-contents="#{[@location[:latitude], @location[:longitude]]}"

.event-legend.col-md-6.col-md-6-cs.hidden-xs style="width: 550px;"
  ul.list-event-legend
    li.compass
      = link_to "Event Legend", "#", class: "btn subcategory", data: {filter: "all"}

    span.compass-img = image_tag "legend.png"
    li
      = link_to image_tag("markers/medi-icon-legend.png", class: "meditation"), "#", class: "subcategory", data: {filter: "meditation"}
      | Meditation
    li
      = link_to image_tag("markers/musi-icon-legend.png", class: "music"), "#", class: "subcategory", data: {filter: "music"}
      | Music
    li
      a class="subcategory" data-filter="march" href="#"
        img alt="March icon" class="march" src="/assets/markers/march-icon-legend.png"
      | March
    li
      = link_to image_tag("markers/multi-icon-legend.png", class: "multiple"), "#", class: "subcategory", data: {filter: "multi"}
      | Multiple

.powered-logo = image_tag "pbu.png"

app/views/home/find_event.js.erb
<%- if @location %>
  <%- if @type.eql? "Worldwide" %>
  <%- else %>
    $("a.location_address").html("<%=j truncate(@location[:address], length: 40) %>");
    $("div.location-nav-right").html("<%=j truncate(@location[:address], length: 40) %>");
    $(".entered-location").val("<%=j truncate(@location[:address], length: 40) %>");
    $(".find-entered-location").val("<%=j truncate(@location[:address], length: 40) %>");
    $(".off-canvas-wrap").removeClass("move-left");
  <% end -%>
  $(".location-status").children("h5").children("span.status-nearby").html("<%=j @nearby %>");
  $(".location-status").children("h5").children("span.status-address").html("<%=j @type %>");

  <%- if @location[:map_type].eql? "earth" %>
    <%= render "locations/google_earth" %>
  <%- else %>
    <%= render "locations/leaflet_categories" %>
  <% end -%>
<%- else %>
  var notif = $('.new-location-change').html("<p>Unable to change location. It might be caused by slow internet connection or the server is down, please try again.</p>");
  notif.show("drop", { direction: "up"}, 200).delay(2000).hide("drop", { direction: "up"}, 300);
<% end -%>

$('#container-projects').css("min-height", 500);

app/views/home/index.html.slim
- content_for :title do
  = "Unify"
- content_for :javascript do
  = javascript_include_tag :maps

- if notice
  p class="alert alert-success alert-dismissible" role="alert"
    button type="button" class="close" data-dismiss="alert"
      span aria-hidden="true"
        | &times;
      span class="sr-only"
        | Close
    = notice

#beta-container.fixed-on-top
  #map style=""
div#content-for-map data-contents="#{@markers}"
div#location-for-map data-contents="#{[@location[:latitude], @location[:longitude]]}"

.event-legend.col-md-6.col-md-6-cs.hidden-xs
  ul.list-event-legend
    li.compass
      = link_to "Event Legend", "#", class: "btn subcategory", data: {filter: "all"}

    span.compass-img = image_tag "legend.png"
    li
      = link_to image_tag("markers/medi-icon-legend.png", class: "meditation"), "#", class: "subcategory", data: {filter: "meditation"}
      | Meditation
    li
      = link_to image_tag("markers/musi-icon-legend.png", class: "music"), "#", class: "subcategory", data: {filter: "music"}
      | Music
    li
      a class="subcategory" data-filter="march" href="#"
        img alt="March icon" class="march" src="/assets/markers/march-icon-legend.png"
      | March
    li
      = link_to image_tag("markers/multi-icon-legend.png", class: "multiple"), "#", class: "subcategory", data: {filter: "multi"}
      | Multiple

.powered-logo = image_tag "pbu.png"