config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :invitations => 'devise/invitations' }
  resources :events do
    collection do
      get "my_events", to: "events#my_events", as: "my_events"
      get "approved_event/:id", :to => 'events#approved_event', :as => "approved_event"
      get "/c/:category", to: "events#categories", as: :category
    end
  end
  root 'home#index'
  post 'create_contact_organizer' => 'home#create_contact_organizer', as: :create_contact_organizer
  get 'find_event' => 'home#find_event', as: :find_event
  post "get_location_by_lat_lng" => "events#get_location_by_lat_lng", as: :get_location_by_lat_lng
  get 'set_timezone' => 'home#set_timezone', as: :set_timezone
  get 'contact_organizer/:id' => 'home#contact_organizer', as: :contact_organizer
  get 'embed' => 'home#embed', as: :embed

end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  geocoded_by :location

  alias_attribute :lat, :latitude
  alias_attribute :long, :longitude

  has_and_belongs_to_many :categories
  # with_options dependent: :destroy do |relation|
  #   relation.has_many :affiliated_organizations
  # end
  belongs_to :user

  scope :approved, -> { where(["status = ? AND latitude IS NOT NULL AND longitude IS NOT NULL", "approved"]) }

  validates_presence_of :title, :category_ids, :start_date, :description, :organizer_name, :organizer_email, :location

  def date_event(timezone)
    timezone.present? ? self.start_date.in_time_zone(timezone) : self.start_date
  end

  def event_type
    if self.categories.count == 1
      self.categories.first.name
    elsif self.categories.count >= 1
      "multi"
    end
  end

  def link
    self.website_link.present? ? self.website_link : "#"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [ :edit, :update, :destroy]
  before_action :set_location, only: [:index, :show, :categories, :edit, :new]

  # GET /events
  # GET /events.json
  def index
    @location = {area: "worldwide", longitude: 0.0, latitude: 0.0}
    @events = Event.where(status: "approved")

    @markers = get_marker_and_location(@events) if @events rescue nil
    @event = Event.new
    @categories = Category.all

    set_title_location(@location)

    render template: "home/index"
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.new
    @event_show = Event.friendly.find(params[:id])
    @categories_event = @event_show.categories
    @categories = Category.all
    @affiliated = AffiliatedOrganization.find(@event_show.affiliated_organization_id) unless @event_show.affiliated_organization_id.blank?
    if @location
      @markers = get_marker_and_location([@event_show]) if @all rescue nil
    end
    set_title_location(@location)
  end

  # GET /events/new
  def new
    @event = Event.new
    @categories = Category.all
    set_title_location(@location)
  end

  # GET /events/1/edit
  def edit
    @categories = Category.all
    @markers = get_marker_and_location([@event])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.affiliated_organization_id = params[:affiliated_organization_id]
    @event.category_ids = params[:category_ids]
    @event.lat = params[:lat]
    @event.long = params[:lng]
    @event.country = params[:country]
    @event.region = params[:administrative_area_level_1]
    @event.postal_code = params[:postal_code]
    @event.estimated_attendees = params[:estimated_attendees]
    respond_to do |format|
      if @event.save
        check_user = User.find_by_email(@event.organizer_email) rescue nil
        if check_user.blank?
          user = User.invite!(email: @event.organizer_email, name: @event.organizer_name) do |u|
            u.skip_invitation = true
          end

          EventCreatedMailer.delay.event_created_information(@event.slug, @event.organizer_email, user.raw_invitation_token)

          @event.update_attribute('user_id', user.id)
        else
          @event.update_attribute('user_id', check_user.id)
          EventCreatedMailer.delay.event_created_information(@event.slug, @event.organizer_email, check_user.invitation_token)
        end

        format.html { redirect_to root_url, notice: 'Thank you for creating an event for World Peace Day, we will confirm your event within 48 hours, and contact you once it has been approved.' }
        format.json { render :index, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.categories.destroy
    @event.affiliated_organization_id = params[:affiliated_organization_id]
    @event.category_ids = params[:category_ids]
    @event.lat = params[:lat]
    @event.long = params[:lng]
    @event.country = params[:country]
    @event.region = params[:administrative_area_level_1]
    @event.postal_code = params[:postal_code]
    @event.estimated_attendees = params[:estimated_attendees]
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event has been updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approved_event
    event = Event.where(id: params[:id]).first
    if params[:unapproved].blank?
      event.update(status: "approved")
      EventApprovedMailer.delay.event_approved_information(event.title, event.slug, event.organizer_email)
    else
      event.update(status: "pending")
    end
    redirect_to :back
  end

  def approved_all_events
    EventApprovedMailer.delay.event_approved_information(event.title, event.slug, event.organizer_email)
  end

  def categories
    @category = params[:category]
    set_project_by_category(@category)
  end

  def get_location_by_lat_lng
    location = Geocoder.search([params[:location][:lat], params[:location][:lng]]).first
    parsed_location = { country_name: location.country, region: location.state, city_name: location.city,
      latitude: location.latitude, longitude: location.longitude, address: location.address,
      postal_code: location.postal_code } if location

      render json: parsed_location
    end

    def my_events
      @event = Event.new
      @categories = Category.all
      @events = Event.where(organizer_email: params[:email]).page(params[:page]).per(3)
    end

    private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :category_id, :website_link, :start_date, :description, :location, :organizer_name, :organizer_email, :affiliated_organization_id, :lat, :long, :status, :country, :region, :city, :postal_code, :estimated_attendees)
  end

  def set_project_by_category(category)
    if category == "all"
      category = "all"
    elsif category == "meditation"
      category = "Meditation / Ceremony / Prayer"
    elsif category == "music"
      category = "Music / Dance / Celebration"
    elsif category == "march"
      category = "March / Action"
    elsif category == "multi"
      category = "multi"
    end

    events = Event.where(["status = ? AND latitude IS NOT NULL AND longitude IS NOT NULL", "approved"])
    @all = []
    events.each do |event|
      if category == "all"
        @all << event
      elsif category == "multi"
        if event.categories.count > 1
          @all << event
        end
      else
        if event.categories.count == 1
          if event.categories.first.name == category
            @all << event
          end
        end
      end
    end

    # set_title_location(@location)
    @markers = get_marker_and_location(@all) if @all

    respond_to do |format|
      if request.xhr?
        format.js
      else
        format.html {render "projects/index"}
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def options_for_attendees(event)
    options_for_select([["1-10", "1-10"], ["10-50", "10-50"], ["50-200", "50-200"], ["200-500", "200-500"] , ["500+", "500+"]], (event.estimated_attendees if event) )
  end
end

app/views/events/_form.html.slim
= form_for(@event, :validate => true ) do |f|
  - if @event.errors.any?
    #error_explanation
      h2
        = pluralize(@event.errors.count, "error")
        | prohibited this event from being saved:
      ul
        - @event.errors.full_messages.each do |message|
          li= message
  .wrap-create-event style="z-index: 999;"
    .header-form-event
      - if request.filtered_parameters["action"].eql?("edit")
        h1.text-center Edit An Event
      - else
        h1.text-center Create An Event
    .body-form-event
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Title of your event
        .col-md-7
          = f.text_field :title, class: "form-control", placeholder: "e.g Global Peace Meditation"
      .clear
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Event Type
        .col-md-7
          - @categories.each do |category|
            .checkbox
              label style=("font-size: 12px;")
                = check_box_tag "category_ids[]", category.id, @event.category_ids.include?(category.id), class: "check_show_marker", id_cat: "#{category.id}"
                = f.label category.name

      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Website/Facebook Link
        .col-md-7
          = f.text_field :website_link, class: "form-control", placeholder: "https://facebook.com"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Event Date & Time
        .col-md-7
          .controls
            div class="input-group date" id="datetimepicker1"
              = f.text_field :start_date, class: "form-control"
              span class="input-group-addon"
                span class="glyphicon-calendar glyphicon"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Event Description
        .col-md-7
          = f.text_area :description, class: "form-control", placeholder: ("Please write a brief description of your event."), rows: "3"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Estimated Attendees
        .col-md-7
          = select_tag :estimated_attendees, options_for_attendees(@event) , class: "form-control",  prompt: "Select One"
          #hidden_field
            .radio
              label
                = radio_button_tag :enter, nil, true
                = f.label "Enter an address"
            .radio
              label
                = radio_button_tag :drag, nil
                = f.label "Drag marker to location"
          #show_map style="display:none"
            | Drag this
            = image_tag "marker.png", id: "content-type", class: "drag show", type: "red", value: "project", style: "margin: 2px 2px; width: 35px;"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Address
        .col-md-7
          = f.text_field :location, class: "form-control geocomplete", placeholder: ("Street Address")
          .field
            = f.hidden_field :country, name: "country"
            = f.hidden_field :region, name: "administrative_area_level_1"
            = f.hidden_field :postal_code, name: "postal_code"
            = f.hidden_field :city, name: "locality"
          .field
            = f.hidden_field :latitude, name: "lat"
          .field
            = f.hidden_field :longitude, name: "lng"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Organizer Name
        .col-md-7
          = f.text_field :organizer_name, class: "form-control", placeholder: "John Doe"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Email Address
        .col-md-7
          = f.text_field :organizer_email, class: "form-control", placeholder: "johndoe@unify.org"
      .form-group style=("display: block;overflow: hidden;")
        .col-md-5.text-right style="font-size:12px;line-height:35px;"
          | Affiliated Organizer
        .col-md-7
          = select_tag :affiliated_organization_id, options_for_select(AffiliatedOrganization.all.map{|a_o| [a_o.name, a_o.id]}, @event.affiliated_organization_id ), prompt: "Select One", class: "form-control"
    .footer-form-event
      button.btn.btn-find.col-md-offset-5 style="margin-right: 3%;margin-left: 33%;" Submit
      | &nbsp;
      button.btn.btn-danger.close-form-create type="reset" Exit

javascript:
  var newAddedMarker = null;

  $(document).ready(function() {
    $('#enter_').click(function(){
      if ($(this).is(':checked')){
        $("#hidden_field").show();
        $("#show_map").hide();
        $("#drag_").prop("checked", false);
      }
    });
    $('#drag_').click(function(){
      if ($(this).is(':checked')){
        $("#show_map").show();
        $("#enter_").prop("checked", false);
      }
    });
    $(".check_show_marker").click(function(){
      if ($(".check_show_marker:checked").length == 1) {
        if ($(".check_show_marker:checked").val() == "1"){
          $("#content-type").attr("src", "/assets/markers/medi-icon.png")
        }else if ($(".check_show_marker:checked").val() == "2"){
          $("#content-type").attr("src", "/assets/markers/musi-icon.png")
        } else if ($(".check_show_marker:checked").val() == "3"){
          $("#content-type").attr("src", "/assets/markers/march-icon.png")
        }else{
          $("#content-type").attr("src", "/assets/markers/multi-icon.png")
        }
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    });
  });
  $('#datetimepicker1').datetimepicker({
    format: "DD-MM-YYYY hh:mm:ss A"
  });

app/views/events/categories.js.erb
<%- if @location %>
  <%- if @type.eql? "Worldwide" %>
  <%- else %>
    $("a.location_address").html("<%=j truncate(@location[:address], length: 40) %>");
    $("div.location-nav-right").html("<%=j truncate(@location[:address], length: 40) %>");
    $(".entered-location").val("<%=j truncate(@location[:address], length: 40) %>");
    $(".find-entered-location").val("<%=j truncate(@location[:address], length: 40) %>");
    $(".off-canvas-wrap").removeClass("move-left");
  <% end -%>
  $(".location-status").children("h5").children("span.status-nearby").html("<%=j @nearby %>");
  $(".location-status").children("h5").children("span.status-address").html("<%=j @type %>");

  <%- if @location[:map_type].eql? "earth" %>
    <%= render "locations/google_earth" %>
  <%- else %>
    <%= render "locations/leaflet_categories" %>
  <% end -%>
<%- else %>
  var notif = $('.new-location-change').html("<p>Unable to change location. It might be caused by slow internet connection or the server is down, please try again.</p>");
  notif.show("drop", { direction: "up"}, 200).delay(2000).hide("drop", { direction: "up"}, 300);
<% end -%>

$('#container-projects').css("min-height", 500);

app/views/events/edit.html.slim
.show_maker_map style="display:none"
  #map style="width:68%; float:right; position:relative;"
.text_show style="display:none; margin-top:0px !important;"
  h1.text-center Loading map...
.hidden_maker_map
  #map-content.content-info-map style=""

#content-for-map data-contents="#{@markers}"
#event-type data-event-type="#{@event.event_type}"
#location-for-map data-contents="#{[@location[:latitude], @location[:longitude]]}"
#content-location-for-map data-content-information="#{[@event.lat, @event.long]}" data-content-type="#{@event.class.to_s.titleize}"

- content_for :javascript do
  = javascript_include_tag :maps
#show style="display:none"
	= render 'form'

javascript:
  $(document).ready(function(){
  	$("#show").show();
  	$('#enter_').click(function(){
  		if ($(this).is(':checked')){
        $("#show_map").hide();
        $("#drag_").prop("checked", false);
        $(".text_show").show();
      	$(".show_maker_map").hide();
        setTimeout(function(){
        	$(".hidden_maker_map").show();
        	$(".text_show").hide();
        }, 3000);
      }
    });
  	$('#drag_').click(function(){
      if ($(this).is(':checked')){
        $("#show_map").show();
        $("#enter_").prop("checked", false);
        $(".hidden_maker_map").hide();
        $(".text_show").show();
        setTimeout(function(){
        	$(".show_maker_map").show();
        	$(".text_show").hide();
        }, 3000);
      }
    });
    if ($(".check_show_marker:checked").length == 1) {
      if ($(".check_show_marker:checked").val() == "1"){
        $("#content-type").attr("src", "/assets/markers/medi-icon.png")
      }else if ($(".check_show_marker:checked").val() == "2"){
        $("#content-type").attr("src", "/assets/markers/musi-icon.png")
      } else if ($(".check_show_marker:checked").val() == "3"){
        $("#content-type").attr("src", "/assets/markers/march-icon.png")
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    }else{
      $("#content-type").attr("src", "/assets/markers/multi-icon.png")
    }
    $(".check_show_marker").click(function(){
      if ($(".check_show_marker:checked").length == 1) {
        if ($(".check_show_marker:checked").val() == "1"){
          $("#content-type").attr("src", "/assets/markers/medi-icon.png")
        }else if ($(".check_show_marker:checked").val() == "2"){
          $("#content-type").attr("src", "/assets/markers/musi-icon.png")
        } else if ($(".check_show_marker:checked").val() == "3"){
          $("#content-type").attr("src", "/assets/markers/march-icon.png")
        }else{
          $("#content-type").attr("src", "/assets/markers/multi-icon.png")
        }
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    });
  });

app/views/events/index.html.slim
h1 Listing events

table
  thead
    tr
      th Title
      th Category
      th Website link
      th Date and time
      th Description
      th Location
      th Organizer name
      th Organizer email
      th Affiliated organization
      th Latitude
      th Longitude
      th colspan="3"

  tbody
    - @events.each do |event|
      tr
        td = event.title
        td = event.category_id
        td = event.link
        td = event.start_date
        td = event.description
        td = event.location
        td = event.organizer_name
        td = event.organizer_email
        td = event.affiliated_organization_id
        td = event.lat
        td = event.long

br

 = link_to 'New Event', new_event_path()

app/views/events/my_events.html.slim
h1 My events

table.table
  thead
    tr
      th Title
      th Category
      th Website link
      th Date and time
      th Description
      th Location
      th Organizer name
      th Organizer email
      th Affiliated organization
      th Latitude
      th Longitude
      th Status
      th colspan="3"

  tbody
    - @events.each do |event|
      tr
        td = event.title
        td = event.category_id
        td = event.website_link
        td = event.start_date
        td = event.description
        td = event.location
        td = event.organizer_name
        td = event.organizer_email
        td = event.affiliated_organization_id
        td = event.lat
        td = event.long
        td = event.status
        td = link_to 'Show', event
        - if event.status.eql?("approved")
          td = link_to 'Edit', edit_event_path(event)
          td = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

br
= paginate @events 

.clearfix

app/views/events/new.html.slim
#beta-container.fixed-on-top
  #map style="width: 100%; !important; float: right;"
div#content-for-map data-contents="#{@markers}"
div#location-for-map data-contents="#{[@location[:latitude], @location[:longitude]]}"
- content_for :javascript do
  = javascript_include_tag :maps
#show style="display:none"
	= render 'form'

javascript:
  $(document).ready(function(){
  	$("#show").show();
  	$('#enter_').click(function(){
  		if ($(this).is(':checked')){
        $("#show_map").hide();
        $("#drag_").prop("checked", false);
        $(".text_show").show();
      	$(".show_maker_map").hide();
        setTimeout(function(){
        	$(".hidden_maker_map").show();
        	$(".text_show").hide();
        }, 3000);
      }
    });
  	$('#drag_').click(function(){
      if ($(this).is(':checked')){
        $("#show_map").show();
        $("#enter_").prop("checked", false);
        $(".hidden_maker_map").hide();
        $(".text_show").show();
        setTimeout(function(){
        	$(".show_maker_map").show();
        	$(".text_show").hide();
        }, 3000);
      }
    });
    if ($(".check_show_marker:checked").length == 1) {
      if ($(".check_show_marker:checked").val() == "1"){
        $("#content-type").attr("src", "/assets/markers/medi-icon.png")
      }else if ($(".check_show_marker:checked").val() == "2"){
        $("#content-type").attr("src", "/assets/markers/musi-icon.png")
      } else if ($(".check_show_marker:checked").val() == "3"){
        $("#content-type").attr("src", "/assets/markers/march-icon.png")
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    }else{
      $("#content-type").attr("src", "/assets/markers/multi-icon.png")
    }
    $(".check_show_marker").click(function(){
      if ($(".check_show_marker:checked").length == 1) {
        if ($(".check_show_marker:checked").val() == "1"){
          $("#content-type").attr("src", "/assets/markers/medi-icon.png")
        }else if ($(".check_show_marker:checked").val() == "2"){
          $("#content-type").attr("src", "/assets/markers/musi-icon.png")
        } else if ($(".check_show_marker:checked").val() == "3"){
          $("#content-type").attr("src", "/assets/markers/march-icon.png")
        }else{
          $("#content-type").attr("src", "/assets/markers/multi-icon.png")
        }
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    });
  });

app/views/events/show.html.slim
.show_maker_map style="display:none"
  #map style="width:100%; float:right; position:relative;"
.text_show style="display:none; margin-top:0px !important;"
  h1.text-center Loading map...
.hidden_maker_map
  #map-content.content-info-map style=""

#content-for-map data-contents="#{@markers}"
#event-type data-event-type="#{@event_show.event_type}"
#location-for-map data-contents="#{[@location[:latitude], @location[:longitude]]}"
#content-location-for-map data-content-information="#{[@event_show.lat, @event_show.long]}" data-content-type="#{@event_show.class.to_s.titleize}"

- content_for :javascript do
  = javascript_include_tag :maps

- if notice
  p class="alert alert-success alert-dismissible" role="alert"
    button type="button" class="close" data-dismiss="alert" style="margin-right: -69%;"
      span aria-hidden="true"
        | &times;
      span class="sr-only"
        | Close
    = notice

.col-md-5.body-see-event style="min-height: 538px;"
  .pull-left style="margin-bottom: 20px;"
    h1 = @event_show.title
    h3 = @event_show.event_type.eql?("multi") ? "Multiple" : @event_show.event_type
    h3 = @event_show.start_date.strftime("%B %d, %l:%M %p")
    h3 = @event_show.location
  .pull-right
    - if admin_user_signed_in? || (user_signed_in? && @event_show.user.eql?(current_user))
      = link_to 'Edit', edit_event_path(@event_show), class: "btn btn-default", style: "margin-top:10px;"

  .clear
  .pull-left.see-event style="min-height: 250px;"
    p = raw truncate_html(strip_tags(@event_show.description), length: 1000)

  .pull-left
    = link_to contact_organizer_path(id: @event_show.id), remote: true, class: "btn btn-default btn-detail", :"data-toggle" => "modal", :"data-target" => "#contact-organizer" do
      | Contact Organizer
      span
        = image_tag "user.png", height: "30px"
    br
    a.btn.btn-default.btn-fb href="http://#{@event_show.website_link}" target="_blank"
      | Official Event Page
      span = image_tag "fb.png", height: "30px", style: "padding-left: 4px;"

  br

  .pull-right style="margin-top: 5px;"
    - unless @affiliated.blank?
      p = image_tag("#{@affiliated.picture_organization}", style: "height: 90px; background: #fff; padding:2px;")


  br
  br
  br

.modal.fade#contact-organizer tabindex="-1" role="dialog" aria-labelledby="ContactOrganizer" aria-hidden="true"
javascript:
  $(document).ready(function(){
    $('#enter_').click(function(){
      if ($(this).is(':checked')){
        $("#show_map").hide();
        $("#drag_").prop("checked", false);
        $(".text_show").show();
        $(".show_maker_map").hide();
        setTimeout(function(){
          $(".hidden_maker_map").show();
          $(".text_show").hide();
        }, 3000);
      }
    });
    $('#drag_').click(function(){
      if ($(this).is(':checked')){
        $("#show_map").show();
        $("#enter_").prop("checked", false);
        $(".hidden_maker_map").hide();
        $(".text_show").show();
        setTimeout(function(){
          $(".show_maker_map").show();
          $(".text_show").hide();
        }, 3000);
      }
    });
    if ($(".check_show_marker:checked").length == 1) {
      if ($(".check_show_marker:checked").val() == "1"){
        $("#content-type").attr("src", "/assets/markers/medi-icon.png")
      }else if ($(".check_show_marker:checked").val() == "2"){
        $("#content-type").attr("src", "/assets/markers/musi-icon.png")
      } else if ($(".check_show_marker:checked").val() == "3"){
        $("#content-type").attr("src", "/assets/markers/march-icon.png")
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    }else{
      $("#content-type").attr("src", "/assets/markers/multi-icon.png")
    }
    $(".check_show_marker").click(function(){
      if ($(".check_show_marker:checked").length == 1) {
        if ($(".check_show_marker:checked").val() == "1"){
          $("#content-type").attr("src", "/assets/markers/medi-icon.png")
        }else if ($(".check_show_marker:checked").val() == "2"){
          $("#content-type").attr("src", "/assets/markers/musi-icon.png")
        } else if ($(".check_show_marker:checked").val() == "3"){
          $("#content-type").attr("src", "/assets/markers/march-icon.png")
        }else{
          $("#content-type").attr("src", "/assets/markers/multi-icon.png")
        }
      }else{
        $("#content-type").attr("src", "/assets/markers/multi-icon.png")
      }
    });
  });